### ISSUE TITLE
redis.exceptions.ResponseError: wrong number of arguments for 'sadd' command

### ISSUE THREAD

**Issue by yunt** [HuiMi24/crysadm#1]
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/yunt/crysadm/crysadm_helper.py", line 307, in background_update_auto_drawcash_user
    r_session.sadd('global:auto.drawcash.cookies', _auto_drawcash_accounts)
  File "/usr/local/lib/python3.4/dist-packages/redis-2.10.5-py3.4.egg/redis/client.py", line 1494, in sadd
    return self.execute_command('SADD', name, *values)
  File "/usr/local/lib/python3.4/dist-packages/redis-2.10.5-py3.4.egg/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, *_options)
  File "/usr/local/lib/python3.4/dist-packages/redis-2.10.5-py3.4.egg/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.4/dist-packages/redis-2.10.5-py3.4.egg/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'sadd' command
一直报这个错误，不知道是我的redis版本不对还是哪里的问题，望大侠指正。

**Comment by HuiMi24** [comment]
在账号管理-我的个人信息里面把自动提现打开就不会报这个错了
