### ISSUE TITLE
这是报错吗

### ISSUE THREAD

**Issue by haogege** [HuiMi24/crysadm#2]
运行python3.4 crysadm_helper.py&这个命令就会显示下面现象，进网页是没有问题

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "crysadm_helper.py", line 299, in clear_offline_user
    if DEBUG_MODE:
NameError: name 'DEBUG_MODE' is not defined

**Comment by HuiMi24** [comment]
已经fix了，忘了commit
